### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by grluk** [grluk/DMT_Journal#1]
- [ ] Combine decode and encoding into one subroutine.
- [ ] Need to decide where to save log files (Dir? setup?)
- [ ] Some form of encryption
- [ ] Add client server infrastructure
- [ ]
